# hand detection config
CAMERA=0
MODEL_COMPLEXITY=1
NUM_HANDS=1
MIN_DETECTION_CONFIDENCE=0.7
MIN_TRACKING_CONFIDENCE=0.9

# model config
TEST_SIZE=0.2
RANDOM_STATE=42
OPTIMIZER='adam'
LOSS='sparse_categorical_crossentropy'
METRICS=['accuracy']
NUMBER_OF_CLASSES=4
EPOCHS=30
TARGET_FRAMES=40